%%getOutput.m
%%pulls network output

function output = getOutput(input,num_conv_layers,filters_per_conv,...
    conv_size,pad,dense_dims,w,b)

numLayers = length(dim);

[a,~,~] = feedforwardAlpha(input,...
num_conv_layers,...
filters_per_conv,...
conv_size,...
pad,...
dense_dims,...
w,...
b);

output = a{numLayers};

end