%%identifyDigit.m

function output = identifyDigit(input,w,b,num_conv_layers,filters_per_conv,conv_size,pad,dense_dims)

[a,~,~] = feedforwardAlpha(input,...
num_conv_layers,...
filters_per_conv,...
conv_size,...
pad,...
dense_dims,...
w,...
b);

output = a{end};

[~,output] = max(output);

end